### ISSUE TITLE
unsupported file type 3

### ISSUE THREAD

**Issue by rain-1** [0intro/libelf#1]
I tested this on a ELF binary I built: `check-envs: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=2f174755e06f81e1f15cd8a415129ae64c9bd5f8, not stripped`

but the library gives this error: `unsupported file type 3`.

**Comment by 0intro** [comment]
Thanks for reporting. The readelf32ehdr and readelf64ehdr functions didn't handle the ET_DYN object file type. I'll submit a fix.
